name:                ray-trace
version:             0.1.0.0
github:              "paploo/ray-trace"
license:             BSD3
author:              "Jeff Reinecke"
maintainer:          "jeff@paploo.net"
copyright:           "2019 Jeff Reinecke"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ray-trace#readme>

dependencies:
- base >= 4.7 && < 5
- hspec >= 2.7.1
- hspec-expectations >= 0.8.2
- hlint

library:
  source-dirs: src

executables:
  ray-trace-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ray-trace

tests:
  ray-trace-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ray-trace
